### ISSUE TITLE
Pass Model to ChildForm

### ISSUE THREAD

**Issue by mstaack** [kristijanhusak/laravel-form-builder#157]
How do i pass a model reference to childs forms?

```
    public function buildForm()
    {
        $this
            ->add('User', 'form', [
                'class' => 'App\Forms\UserForm',
                'formOptions' => [],
                'model' => $user,
            ])->add('Company', 'form', [
                'class' => 'App\Forms\CompanyForm',
            ]);
    }
```
'model'=>$user  is not working...form is rendered, but empty

**Comment by kristijanhusak** [comment]
Is `$user` the same model as the one that is passed to the main form, or it is something different?

**Comment by mms-hamburg** [comment]
i can even use Auth::user()  and it is still not workin....
attributes names are okay

**Comment by kristijanhusak** [comment]
Since Child form is form type like any other, you can pass it as `value`:
```php
    public function buildForm()
    {
        $this
            ->add('User', 'form', [
                'class' => 'App\Forms\UserForm',
                'formOptions' => [],
                'value' => $user,
            ])->add('Company', 'form', [
                'class' => 'App\Forms\CompanyForm',
            ]);
    }
```

Another way that is also possible, is to pass `model` from `formOptions`:

```php
    public function buildForm()
    {
        $this
            ->add('User', 'form', [
                'class' => 'App\Forms\UserForm',
                'formOptions' => [
                    'model' => $user
                ],
            ])->add('Company', 'form', [
                'class' => 'App\Forms\CompanyForm',
            ]);
    }
```
This 2nd solution will not work if the model does not have all user data namespaced by `User`, until i fix it, which will be done now, but only on master branch.

**Comment by mms-hamburg** [comment]
will give this a try later

**Comment by tormit** [comment]
```php
public function buildForm()
    {
        $this
            ->add('User', 'form', [
                'class' => 'App\Forms\UserForm',
                'formOptions' => [],
                'value' => $user,
            ])->add('Company', 'form', [
                'class' => 'App\Forms\CompanyForm',
            ]);
    }
```

This way works.
Still, when I pass instance of Form(with model attached) to 'class', it should take existing values from there.

**Comment by kristijanhusak** [comment]
You are passing path to UserForm class as string, not an instance. You can pass an instance like this:

```php
public function buildForm()
    {
        $userForm = $this->formBuilder->create('App\Forms\UserForm', ['model' => $user]);
        $this
            ->add('User', 'form', [
                'class' => $userForm
            ])->add('Company', 'form', [
                'class' => 'App\Forms\CompanyForm',
            ]);
    }
```

**Comment by tormit** [comment]
I'm sorry. I just copied the snippet. My working code is something like this:
```php
public function buildForm()
    {
        $userForm = $this->formBuilder->create('App\Forms\UserForm', ['model' => $user]);
        $this
            ->add('User', 'form', [
                'class' => $userForm,
                'value' => $user
            ])->add('Company', 'form', [
                'class' => 'App\Forms\CompanyForm',
            ]);
    }
```

The problem is that it should take the 'value' automatically from $userForm model.

**Comment by kristijanhusak** [comment]
Oh, it doesn't? I will check it. Thanks.

**Comment by kristijanhusak** [comment]
@tormit It's fixed in latest release (1.6.30). Do a composer update and check if it works. Thanks for reporting.

**Comment by tormit** [comment]
Still does not work.
Maybe there is something with named forms, because both of my form are named(parent and child forms).

**Comment by kristijanhusak** [comment]
According to your snippet, your child form is not named:
```php
  $userForm = $this->formBuilder->create('App\Forms\UserForm', ['model' => $user]);
```

**Comment by tormit** [comment]
Yes, but in my real project both forms are named.

**Comment by kristijanhusak** [comment]
You should mention that. I will check it out.

**Comment by ikostic** [comment]
Hi Kristijan,

my previosly working code stopped working after composer update.

This is working code:

in controller initializing parent form with model

$form = $formBuilder->create('Something\Forms\AdminUserForm', [
			'method' => 'PATCH',
			'action' => ['AdminUserController@update', $id],
			'model' => $user_arr
		]);

in parent form class:

public function buildForm()
    {
.....
        $this
            ->add('Id', 'hidden')
            ->add('Name', 'text')
            ->add('Login', 'text')
            ->add('Email', 'email')
            ->add('Status', 'select', [
                'choices' => ['NEW' => 'NEW','APPROVED' => 'APPROVED','ON HOLD' => 'ON HOLD','DELETED' => 'DELETED'],
            ])
            ->add('Credentials', 'form',[
                'wrapper' => [
                    'class' => 'form-group credential-padding'
                ],
                'class' => $this->formBuilder->create('Something\Forms\AdminCredentialForm')
            ])
            ->add('LanguageId', 'select', [
                'label' => 'Default Language',
                'choices' => $languages,
            ]);
    }

in child form class:

public function buildForm()
    {
        $credentials = AdminCredentialQuery::create()->find();
        $credentials_arr = array();
        foreach($credentials as $credential){
            $name = $credential->getName();
            $id = $credential->getId();
            $this
                ->add($id, 'choice', [
                    'label' => $name,
                    'choices' => ['read' => 'read', 'write' => 'write', 'exec' => 'exec'],
                    'help_block' => ['credential_tag' => true],
                    'expanded' => true,
                    'multiple' => true
                ]);
        }
    }

Can you help me on this matter, not sure how to resolve it because it worked 3-4 months ago and after update it stopped working.

Regards

**Comment by kristijanhusak** [comment]
@ikostic what exactly is not working? Do you have any exception, something's missing, or what?

**Comment by ikostic** [comment]
Parent form values are populated from model but child form values are not populated. Checkboxes are empty. No errors, no exceptions, simply checkboxes are not checked.

**Comment by kristijanhusak** [comment]
@ikostic ok, i'll check it out and let you know. Thanks for reporting.

**Comment by kristijanhusak** [comment]
@ikostic I tested it out, it works ok here.
I guess `Credentials` are not populated. Can you paste data from `$user_arr` that you pass when creating form?
Also what is returned from `AdminCredentialQuery::create()->find()` could be useful.

**Comment by ikostic** [comment]
$user_arr:

Array
(
    [Id] => 1
    [Name] => Igor Kostic
    [Login] => ikostic
    [Email] => igorkg@gmail.com
    [Status] => APPROVED
    [LanguageId] => 1
    [Credentials] => Array
        (
            [1] => Array
                (
                    [read] => read
                    [write] => write
                )

            [2] => Array
                (
                    [read] => read
                    [write] => write
                )

            [3] => Array
                (
                    [read] => read
                    [write] => write
                )

            [4] => Array
                (
                    [read] => read
                    [write] => write
                )

            [5] => Array
                (
                    [read] => read
                    [write] => write
                )

            [6] => Array
                (
                    [read] => read
                    [write] => write
                )

            [7] => Array
                (
                    [read] => read
                    [write] => write
                )

            [8] => Array
                (
                    [read] => read
                    [write] => write
                )

            [9] => Array
                (
                    [read] => read
                    [write] => write
                )

            [10] => Array
                (
                    [read] => read
                    [write] => write
                )

            [11] => Array
                (
                    [read] => read
                    [write] => write
                )
        )
)

AdminCredentialQuery::create()->find() is returning object:

[data:protected] => Array
        (
            [0] => Something\AdminCredential Object
                (
                    [new:protected] => 
                    [deleted:protected] => 
                    [modifiedColumns:protected] => Array
                        (
                        )

                    [virtualColumns:protected] => Array
                        (
                        )

                    [id:protected] => 1
                    [group_id:protected] => 1
                    [name:protected] => ac_manage
                    [title:protected] => USERS
                    [sequence:protected] => 10
                    [created_at:protected] => DateTime Object
                        (
                            [date] => 2015-04-28 20:38:42.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                    [updated_at:protected] => DateTime Object
                        (
                            [date] => 2015-04-28 20:38:42.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                    [aAdminCredentialGroup:protected] => 
                    [collAdminUserCredentials:protected] => 
                    [collAdminUserCredentialsPartial:protected] => 
                    [alreadyInSave:protected] => 
                    [adminUserCredentialsScheduledForDeletion:protected] => 
                )

            [1] => Something\AdminCredential Object
                (
                    [new:protected] => 
                    [deleted:protected] => 
                    [modifiedColumns:protected] => Array
                        (
                        )

                    [virtualColumns:protected] => Array
                        (
                        )

                    [id:protected] => 2
                    [group_id:protected] => 1
                    [name:protected] => translation
                    [title:protected] => TRANSLATIONS
                    [sequence:protected] => 20
                    [created_at:protected] => DateTime Object
                        (
                            [date] => 2015-04-28 20:53:54.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                    [updated_at:protected] => DateTime Object
                        (
                            [date] => 2015-04-28 20:53:54.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                    [aAdminCredentialGroup:protected] => 
                    [collAdminUserCredentials:protected] => 
                    [collAdminUserCredentialsPartial:protected] => 
                    [alreadyInSave:protected] => 
                    [adminUserCredentialsScheduledForDeletion:protected] => 
                )

            [2] => Something\AdminCredential Object
                (
                    [new:protected] => 
                    [deleted:protected] => 
                    [modifiedColumns:protected] => Array
                        (
                        )

                    [virtualColumns:protected] => Array
                        (
                        )

                    [id:protected] => 3
                    [group_id:protected] => 2
                    [name:protected] => api_test
                    [title:protected] => API_TEST
                    [sequence:protected] => 100
                    [created_at:protected] => DateTime Object
                        (
                            [date] => 2015-04-30 15:54:59.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                    [updated_at:protected] => DateTime Object
                        (
                            [date] => 2015-04-30 15:54:59.000000
                            [timezone_type] => 3
                            [timezone] => UTC
                        )

                    [aAdminCredentialGroup:protected] => 
                    [collAdminUserCredentials:protected] => 
                    [collAdminUserCredentialsPartial:protected] => 
                    [alreadyInSave:protected] => 
                    [adminUserCredentialsScheduledForDeletion:protected] => 
                )

I was developing this code during month may. In that moment everything worked ok and after that i didn't change anything on the code or database.

Thanks

**Comment by kristijanhusak** [comment]
@ikostic if you published the views, check them out and replace all `default_value` with `value`.

**Comment by ikostic** [comment]
You are right. I have checked form field templates in resources folder and replaced default_value with value. Now functionality is working ok.

Thanks on your support!!!

Regards,

Igor Kostic

**Comment by kristijanhusak** [comment]
@tormit when you give a name to a child form, what do you expect to get as a name in fields of those child form? For example, in your case when you do not give name to a child form, you will get something like `User[email]` or `Company[name]`. What you expect to happen when you name it?

**Comment by tormit** [comment]
I expect the field name to be like _parent_form_name[child_form_name][field_name]_.
Also deeper nesting would be appreciated _parent_form_name[child_form_name][child_child_form_name][...][field_name]_ in case child form itself has an child form and so on.

**Comment by kristijanhusak** [comment]
@tormit I pushed a fix to a master branch. I would really appreciate if you could test it with `dev-master` to see if it's working.

**Comment by kristijanhusak** [comment]
@tormit This is released in 1.6.31.

**Comment by tormit** [comment]
OK. I'll check it out soon.
I'm sorry that I haven't got time to give comprehensive feedback on this issue, though there were still some problems with it.

**Comment by kristijanhusak** [comment]
@tormit what is the status of this issue?

**Comment by tormit** [comment]
Passing model seems to be working now.
But, it is passed as array. It needs to be original object. For example when using Laravel Form Builder with Laravel-Translatable(https://github.com/dimsav/laravel-translatable), the translation form expects model as an instance.

**Comment by kristijanhusak** [comment]
I already explained problematic in https://github.com/kristijanhusak/laravel-form-builder/issues/184 . You can temporarily pass the model with `data` and use it how you need.

**Comment by tormit** [comment]
When testing with latest dev version, model is passed as object and everything seems to be working.

**Comment by kristijanhusak** [comment]
@tormit it works when u pass it as data or normally?

**Comment by tormit** [comment]
When passing normally as model.

Like this:
```php
$this->add(
    $locale,
    'form',
    [
        'class' => $this->getFormBuilder()->create(ContentFormTranslation::class, ['model' => $this->getModel()->translate($locale)]),
    ]
);
```

**Comment by kristijanhusak** [comment]
Great! I'm closing this than. Thanks for reporting.
