### ISSUE TITLE
Prototype being created with data values from model

### ISSUE THREAD

**Issue by hackel** [kristijanhusak/laravel-form-builder#74]
This issue is related to #73.  The form's data-prototype attribute is created correctly, but the generated HTML is including the values from the third (child) model in the collection, just like the other child forms.  Obviously these values should be empty in a prototype.  I'm creating the prototype just as described in the documentation:
```html
<div class="collection-container" data-prototype="{{ form_row($form->contacts->prototype()) }}">
    {!! form_row($form->contacts) !!}
</div>
```
I'll try to keep debugging this myself, but any help would be appreciated.

**Comment by kristijanhusak** [comment]
This should be also fixed with the latest update that i mentioned in https://github.com/kristijanhusak/laravel-form-builder/issues/73 . If it's working fine, please close the issue. Thanks.

**Comment by hackel** [comment]
Unfortunately I'm still getting a prototype with the values from the last item in my collection with 1.4.05.

**Comment by kristijanhusak** [comment]
I fixed it, should be working properly now. Please test it.

**Comment by hackel** [comment]
Working great now, thanks!  Is a way to set a default value for the prototype?  I tried setting `'default_value' => 'x',` in my form field options, but this gets overwritten with null at some point.

**Comment by kristijanhusak** [comment]
I fixed it on master branch, but still didn't tagged and updated on packagist because i want to add some more things.
